### ISSUE TITLE
missing whitespaces between dynamic nodes

### ISSUE THREAD

**Issue by dreyks** [apotonick/erbse#2]
```erb
<div class="class1 <%= 'class2' %> <%= 'class3' %>></div>
```

evaluates to 
```html
<div class="class1 class2class3"></div>
```

```console
2.3.3 :001 > require 'erbse'
 => true
2.3.3 :002 > eval Erbse::Engine.new.call(%{<div class="class1 <%= 'class2' %> <%= 'class3' %>"></div>})
 => "<div class=\"class1 class2class3\"></div>"
2.3.3 :003 >
```

is this intended?

**Comment by apotonick** [comment]
It's not!

**Comment by dreyks** [comment]
I think you should add `newlines` [here](https://github.com/apotonick/erbse/blob/0bc0241bc2dec1cc526e5275b894dcbe561912ef/lib/erbse/parser.rb#L40)

**Comment by dreyks** [comment]
oh wait, it's worse. Anything between two erb codes is missing, not just whitespaces

```console
2.3.3 :001 > require 'erbse'
 => true
2.3.3 :002 > eval Erbse::Engine.new.call("<%= 'one' %> two <%= 'three' %>")
 => "onethree"
```

**Comment by dreyks** [comment]
Ah no, the cause of this is [here](https://github.com/apotonick/erbse/blob/0bc0241bc2dec1cc526e5275b894dcbe561912ef/lib/erbse/parser.rb#L31)

**Comment by apotonick** [comment]
Sorry @dreyks for not patching. @Scharrels will take care of it tomorrow. :wink:
