### ISSUE TITLE
HTML Escaping

### ISSUE THREAD

**Issue by der-flo** [apotonick/erbse#5]
I'm using Erbse outside the context of Cells. For me, it would make sense if Erbse could do the escaping by default. See Erbuis: https://github.com/rtomayko/tilt/blob/master/lib/tilt/erubis.rb#L22

How would you implement such a feature? Perhaps I can do this by myself.

BTW: The capturing feature is awesome. No other templating engine provides this.

**Comment by apotonick** [comment]
Thanks Flo, the capturing was the only reason I wrote this gem :joy: !

Either Temple provides something for escaping, or we have to build it into Erbse as an optional feature.

**Comment by der-flo** [comment]
Jep, Template has something in its toolbelt ([Temple::Filters::Escapable](https://github.com/judofyr/temple/blob/master/lib/temple/filters/escapable.rb)), but Erbse is not prepared for using this directly. I made some progress with hacking up `Erbse::Parser` (surrounding content with `[:escape, true, content]` and putting some `.html_safe` in), but I would need to make myself more familiar with the  Temple and Erbse code. That will take more time.

@apotonick Are the needed code changes obvious for you?

**Comment by apotonick** [comment]
Ah, ok, cool! I should be able to help here. Have you found any examples where they use those filters (e.g. in their test suite)?

**Comment by der-flo** [comment]
They use the filter in their own ERb implementation ([Temple::ERB::Engine](https://github.com/judofyr/temple/blob/master/lib/temple/erb/engine.rb), especially [Temple::ERB::Parser](https://github.com/judofyr/temple/blob/master/lib/temple/erb/parser.rb) - [Line 30](https://github.com/judofyr/temple/blob/master/lib/temple/erb/parser.rb#L30) seems interesting) and wrote some tests ([test_escapable.rb](https://github.com/judofyr/temple/blob/master/test/filters/test_escapable.rb), [test_erb.rb](https://github.com/judofyr/temple/blob/master/test/test_erb.rb)). These are the most interesting code parts.

**Comment by apotonick** [comment]
Ok, it is as I expected: You wrap static and dynamic content into an [`:escape, <here goes the original>]` expression. Have you checked our parser implementation? It is only a few lines of code, want to give it a try?

**Comment by der-flo** [comment]
I made some progress, but capturing content and returning it `html_safe?` seems quite tricky. I'll continue next week.

**Comment by apotonick** [comment]
It should really just be the filter added... I'd help if I *had* time... :laughing:

**Comment by der-flo** [comment]
Capturing works quite well with Slim, so I don't need this feature anymore.
